//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_centar_zadatak.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KontaktOsoba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KontaktOsoba()
        {
            this.MailKontakts = new HashSet<MailKontakt>();
            this.TelefonKontakts = new HashSet<TelefonKontakt>();
        }
    
        public int ID { get; set; }
        public int IDpreduzeca { get; set; }
        [Required]
        public string Ime { get; set; }
        
        [Required]
        public string Prezime { get; set; }
        [DisplayName("Radno mesto")]
        [Required]
        public string RadnoMesto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailKontakt> MailKontakts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelefonKontakt> TelefonKontakts { get; set; }
        public virtual Preduzece Preduzece { get; set; }
    }
}
