//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_centar_zadatak.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MailKontakt
    {
        public int IDKontakt { get; set; }
        [Required]
        [DisplayName("Oznaka tipa")]
        public string OznakaTip { get; set; }
        [Required]
        public string Adresa { get; set; }
        [Required]
        public bool Greska = false;
        public virtual KontaktOsoba KontaktOsoba { get; set; }
    }
}
