//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_centar_zadatak.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektniZadatakEntities1 : DbContext
    {
        public ProjektniZadatakEntities1()
            : base("name=ProjektniZadatakEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KontaktOsoba> KontaktOsobas { get; set; }
        public virtual DbSet<MailKontakt> MailKontakts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TelefonKontakt> TelefonKontakts { get; set; }
        public virtual DbSet<Preduzece> Preduzeces { get; set; }
    }
}
