//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_centar_zadatak.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Preduzece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preduzece()
        {
            this.KontaktOsobas = new HashSet<KontaktOsoba>();
        }
        
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        
        public int ID { get; set; }
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        [DisplayName("Naziv preduzeca")]
        public string NazivPreduzeca { get; set; }
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        public string Adresa { get; set; }
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        public string Opstina { get; set; }
        [DisplayName("Postanski broj")]
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        [MaxLength(5,ErrorMessage ="Postanski broj moze imati najvise 5 cifara")]
        public string PostanskiBR { get; set; }
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        [Key]
        [MaxLength(8,ErrorMessage ="Maticni broj ne moze imati vise od 8 cifara")]
        [DisplayName("Maticni broj")]
        public string MatBR { get; set; }
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        [MaxLength(9, ErrorMessage = "PIB ne moze imati vise od 9 cifara")]
        
        public string PIB { get; set; }
        [Required(ErrorMessage = "Ovo polje mora biti popunjeno!")]
        [MaxLength(20, ErrorMessage = "Broj racuna ne moze imati vise od 20 cifara")]
        [DisplayName("Broj racuna")]
        public string BrojRacuna { get; set; }
        [DataType(DataType.Url)]
        [DisplayName("Web stranica")]
        public string WebStranica { get; set; }
        [DisplayName("Fotografija pecata")]
        
        public  string FotografijaPecata { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public string Beleska { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KontaktOsoba> KontaktOsobas { get; set; }
    }
}
